---
title: "OATLD manuscript figures"
author: "J. Meyer"
date: "2025-09-05"
output: html_document
---


```{r}
#Load the libraries
library(phyloseq)
library(CoDaSeq)
library(zCompositions)
library(cowplot)
library(ggplot2)
library(vegan)
library(tidyverse)
library(reshape2)
library(ggpubr)
library(FSA)
library(DESeq2)
writeLines(capture.output(sessionInfo()), "sessionInfo.txt")
```


Figure A - Beta diversity PCA and dispersion

```{r}
otu <- read.table("silva_nochloronomito_otu_table_ps_f2.txt",sep="\t",header=TRUE, row.names=1)
taxon <- read.table("silva_nochloronomito_taxa_table_ps_f2.txt",sep="\t",header=TRUE,row.names=1)
samples<-read.table("metadata_noblanks.txt",sep="\t",header=T,row.names=1)

OTU = otu_table(otu, taxa_are_rows=FALSE)
taxon<-as.matrix(taxon)
TAX = tax_table(taxon)
sampledata = sample_data(samples)
ps_f2 <- phyloseq(otu_table(otu, taxa_are_rows=FALSE), 
               sample_data(samples), 
               tax_table(taxon))
ps_f2 # 1202 taxa and 77 samples

### Principal Components Analysis
# First, replace 0 values with an estimate (because normalization is taking log, can't have 0)
# Also transposing here, need samples as rows
d.czm <- cmultRepl(t(otu), method="CZM", label=0, z.warning = 0.999)
# Perform the center-log-ratio (CLR) transformation 
d.clr <- codaSeq.clr(d.czm)
# transpose matrix of CLR transformed data for ordination and dendrogram
E.clr <- t(d.clr)
# plot compositional PCA biplot (perform a singular value decomposition)
d.pcx <- prcomp(E.clr)
# calculate percent variance explained for the axis labels
pc1 <- round(d.pcx$sdev[1]^2/sum(d.pcx$sdev^2),2)
pc2 <- round(d.pcx$sdev[2]^2/sum(d.pcx$sdev^2),2)
df_out <- as.data.frame(d.pcx$x)
dist.clr <- dist(E.clr)

# Set asthetics for plot
palette2<- c("Diseased" = "#d1495b", "Unaffected" = "#edae49", "Healthy" = "#00798c")
sample_data(ps_f2)$Site<-factor(sample_data(ps_f2)$Site, levels=c("Looe", "Grecian/KLDR", "Carysfort"))
theme_set(theme_bw()+theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank()))

p1<-ggplot(df_out,aes(x=PC1,y=PC2,fill=sample_data(ps_f2)$Condition, shape=sample_data(ps_f2)$Site))
p1<-p1+geom_point( size=3.5)+
  theme(axis.title = element_text(size=14))+
  theme(axis.text=element_text(size=12))+
  theme(legend.title = element_text(size=14))+
  theme(legend.text = element_text(size=12))+
  theme(legend.position = "right")+
  coord_fixed()+
  labs(fill = "Condition", shape="Site")+
  scale_fill_manual(values = palette2, breaks = c("Healthy", "Unaffected", "Diseased"))+
  scale_shape_manual(values = c(23, 24, 21))+
  labs(x = "Principal Component 1: 30%", y = "Principal Component 2: 5%") +
  theme(axis.text.x=element_text(colour="black"))+
  theme(axis.text.y=element_text(colour="black"))+
  guides(fill = guide_legend(order = 1,override.aes = list(shape = 21)), shape = guide_legend(order = 2))
p1

pdf("PCA.pdf", ,bg ="white")
p1
dev.off()

### Beta Diversity Dispersion - Condition
#calculate multivariate dispersions based on Condition
mod <-betadisper(dist.clr, sampledata$Condition)
anova(mod)
plot(mod)
## Compute mean distance to centroid per group
#this just prints values on the console
tapply(mod$distances, sampledata$Condition, mean)
## Same, but variance instead
tapply(mod$distances, sampledata$Condition, var)

#Get the distances to centroid from the model
mod$distances
dis <- mod$distances
dis.melt <- melt(dis)
#move rownames to columns so we can merge the dispersion values and metadata
dis.melt$Sample <- rownames(dis.melt)
samples$Sample <- rownames(samples)
#merge metadata and dispersion 
dis.condition <- merge(samples, dis.melt)
#rename column
colnames(dis.condition)[4] <- "distance"

shapiro.test(dis.condition$distance) #Not normally distributed, use kruskal test
distance.test<- kruskal.test(distance ~ Condition, data=dis.condition)
print(distance.test)
capture.output(distance.test,file="kruskal_distance_to_centroid.txt")

#Post Hoc Test
dunnTest(distance ~ Condition,
  data = dis.condition,
  method = "bonferroni"
)

# Set asthetics for plot
palette2<- c("Diseased" = "#d1495b", "Unaffected" = "#edae49", "Healthy" = "#00798c")
dis.condition$Condition<-factor(dis.condition$Condition, levels=c("Healthy", "Unaffected", "Diseased"))
theme_set(theme_bw()+theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank()))

p2<-ggplot(dis.condition, aes(x=Condition, y=distance)) +
  geom_boxplot() +
  geom_point(position=position_jitter(width=.1, height=0),aes(fill=Condition),size=4,pch=21) +
  scale_fill_manual(values = palette2) +
  ylab("Distance to Centroid")+
  theme(axis.text.x = element_text(colour="black"))+
  theme(axis.text.y = element_text(colour="black"))+
  theme(axis.text.x = element_text(size = 20))+
  theme(axis.text.y = element_text(size = 20))+
  theme(axis.title.x = element_blank())+
  theme(axis.title.y = element_text(size = 22))+
  theme(legend.position = "none") +
  stat_compare_means(
    comparisons = list(c("Diseased", "Healthy")),
    method = "t.test",
    label = "p.signif")
p2

pdf("Dispersion.pdf",bg ="white")
p2
dev.off()
```


SOM: Alpha diversity


```{r}
# Set asthetics for plot
palette2<- c("Diseased" = "#d1495b", "Unaffected" = "#edae49", "Healthy" = "#00798c")
sample_data(ps_f2)$Condition<-factor(sample_data(ps_f2)$Condition, levels=c("Healthy", "Unaffected", "Diseased"))
sample_data(ps_f2)$Con<-factor(sample_data(ps_f2)$Con, levels=c("H", "U", "D"))
theme_set(theme_bw()+theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank()))

richness<- plot_richness(ps_f2, x="Con", measures=c("Observed","Chao1","Shannon"))
richness$layers <- richness$layers[-1]
p3<-richness + 
  geom_boxplot( alpha = 0.6,aes(fill=Condition))+
  geom_point(position=position_jitter(width=.1, height=0),aes(fill=Condition),size=4,pch=21)+
  theme(axis.text.x = element_text(angle=0,hjust=0.5,size=14,colour="black"))+
  theme(axis.text.y = element_text(size=14,colour="black"))+
  theme(axis.title.x = element_blank())+
  theme(axis.title.y = element_text(size = 16))+
  theme(strip.text.x=element_text(size=16),strip.background=element_rect(fill="white"))+
  theme(legend.title = element_text(size = 16))+
  theme(legend.text = element_text(size = 14)) +
  scale_fill_manual(values = palette2)
p3

pdf("AlphaDiversity.pdf",width=8.25, height=6)
p3
dev.off()

```




Figure B - CLAM test

```{r}
# CLAM test
otu <- read.table("silva_nochloronomito_otu_table_ps_f2.txt",sep="\t",header=TRUE, row.names=1)
taxon <- read.table("silva_nochloronomito_taxa_table_ps_f2.txt",sep="\t",header=TRUE,row.names=1)
samples<-read.table("metadata_noblanks.txt",sep="\t",header=T,row.names=1)

OTU = otu_table(otu, taxa_are_rows=FALSE)
taxon<-as.matrix(taxon)
TAX = tax_table(taxon)
sampledata = sample_data(samples)
ps_f2 <- phyloseq(otu_table(otu, taxa_are_rows=FALSE), 
               sample_data(samples), 
               tax_table(taxon))
ps_f2 # 1202 taxa and 77 samples

ps_f2_HH_DD<- subset_samples(ps_f2, Condition == "Healthy" | Condition == "Diseased")
ps_f2_HH_DD #1202 taxa and 52 samples

ps_f2_HH_DD_pruned <- prune_taxa(taxa_sums(ps_f2_HH_DD) > 0, ps_f2_HH_DD)
ps_f2_HH_DD_pruned #1160 taxa and 52 samples

otu_table <- as.data.frame(otu_table(ps_f2_HH_DD_pruned))
sample_data <- as.data.frame(sample_data(ps_f2_HH_DD_pruned))
# Assuming 'group' is a column in your sample data
env_var <- sample_data$Condition
clam_results_ps <- vegan::clamtest(otu_table, env_var, alpha = 0.05, specialization = 2/3)
print(clam_results_ps)
summary(clam_results_ps)


c("D" = "#d1495b", "U" = "#edae49", "H" = "#00798c")


colors <- c("Generalist" = "gray",
            "Specialist_Healthy" = "#00798c", 
            "Specialist_Diseased" = "#d1495b", 
            "Too_rare" = "black")

labels<- c("Generalist (n=298)", "Specialist_Healthy (n=548)", "Specialist_Diseased (n=160)", "Too_rare (n=154)")

pdf("CLAM_plot.pdf", width = 8.25, height = 6,bg ="white")
plot(clam_results_ps, xlab = "Diseased samples (ASV abundance + 1)", ylab = "Healthy samples (ASV abundance + 1)", 
     pch = c(1,16,16,1), col=colors, col.lines = c("black", "black", "black"), 
     lty = c(2,2,2), cex=1.5, position = "topleft")
legend("topleft",legend = labels, pch = c(1,16,16,1), col=colors)
dev.off()

#Cribrihabitans
x_5<- clam_results_ps$Total_Diseased[clam_results_ps$Species=="TACGGAGGGGGTTAGCGTTGTTCGGAATTACTGGGCGTAAAGCGCGCGTAGGCGGATTGGAAAGTTGGGGGTGAAATCCCGGGGCTCAACCCCGGAACTGCCTTCAAAACTCCCAGTCTAGAGTTCGAGAGAGGTGAGTGGAATTCCGAGTGTAGAGGTGAAATTCGTAGATATTCGGAGGAACACCAGTGGCGAAGGCGGCTCACTGGCTCGATACTGACGCTGAGGTGCGAAAGTGTGGGGAGCAAACAGG"] +1 
y_5<- clam_results_ps$Total_Healthy[clam_results_ps$Species=="TACGGAGGGGGTTAGCGTTGTTCGGAATTACTGGGCGTAAAGCGCGCGTAGGCGGATTGGAAAGTTGGGGGTGAAATCCCGGGGCTCAACCCCGGAACTGCCTTCAAAACTCCCAGTCTAGAGTTCGAGAGAGGTGAGTGGAATTCCGAGTGTAGAGGTGAAATTCGTAGATATTCGGAGGAACACCAGTGGCGAAGGCGGCTCACTGGCTCGATACTGACGCTGAGGTGCGAAAGTGTGGGGAGCAAACAGG"] +1

#Ferrimonas
x_12<- clam_results_ps$Total_Diseased[clam_results_ps$Species=="TACGGAGGGTGCGAGCGTTAATCGGAATCACTGGGCGTAAAGCGCATGCAGGCGGTTTGCTAAGCGAGATGTGAAAGCCCCGGGCTTAACCTGGGAACTGCATTTCGAACTGGCGAACTAGAGTCTTGTAGAGGGGGGTAGAATTTCAGGTGTAGCGGTGAAATGCGTAGAGATCTGAAGGAATACCAGTGGCGAAGGCGGCCCCCTGGACAAAGACTGACGCTCAGATGCGAAAGCGTGGGGAGCAAACAGG"] +1 
y_12<- clam_results_ps$Total_Healthy[clam_results_ps$Species=="TACGGAGGGTGCGAGCGTTAATCGGAATCACTGGGCGTAAAGCGCATGCAGGCGGTTTGCTAAGCGAGATGTGAAAGCCCCGGGCTTAACCTGGGAACTGCATTTCGAACTGGCGAACTAGAGTCTTGTAGAGGGGGGTAGAATTTCAGGTGTAGCGGTGAAATGCGTAGAGATCTGAAGGAATACCAGTGGCGAAGGCGGCCCCCTGGACAAAGACTGACGCTCAGATGCGAAAGCGTGGGGAGCAAACAGG"] +1

#Aurantivirga
x_16<- clam_results_ps$Total_Diseased[clam_results_ps$Species=="TACGGAGGGTGCAAGCGTTATCCGGAATCATTGGGTTTAAAGGGTCCGCAGGCGGTCAATTAAGTCAGAGGTGAAATCCCATAGCTTAACTATGGAACTGCCTTTGATACTGGTTGACTTGAGTTATACGGAAGTAGATAGAATAAGTAGTGTAGCGGTGAAATGCATAGATATTACTTAGAATACCGATTGCGAAGGCAGTCTACTACGTATATACTGACGCTCATGGACGAAAGCGTGGGGAGCGAACAGG"] +1 
y_16<- clam_results_ps$Total_Healthy[clam_results_ps$Species=="TACGGAGGGTGCAAGCGTTATCCGGAATCATTGGGTTTAAAGGGTCCGCAGGCGGTCAATTAAGTCAGAGGTGAAATCCCATAGCTTAACTATGGAACTGCCTTTGATACTGGTTGACTTGAGTTATACGGAAGTAGATAGAATAAGTAGTGTAGCGGTGAAATGCATAGATATTACTTAGAATACCGATTGCGAAGGCAGTCTACTACGTATATACTGACGCTCATGGACGAAAGCGTGGGGAGCGAACAGG"] +1

#Mycoplasma
x_13<- clam_results_ps$Total_Diseased[clam_results_ps$Species=="TACATAGGCCCCAAGCGTTATCCGGATTTACTGGGCGTAAAGAGTGCGCAGGTGATTTCACAAGTCTGTATTGAAAGGCTGGAGCTCAACTCCAGTTTGGTATGGAAACTGTGTTATTAGATTATGATAGAGGTTAGCGGAATTCCTAATGTAGCGGTGGAATGCGTAGATATTAGGAGGAACACCAAAAGCGAAGGCAGCTAACTGGGTCATTAATGACACTGGTGCACGAAAGCGTGGGGAGCAAACAGG"] +1 
y_13<- clam_results_ps$Total_Healthy[clam_results_ps$Species=="TACATAGGCCCCAAGCGTTATCCGGATTTACTGGGCGTAAAGAGTGCGCAGGTGATTTCACAAGTCTGTATTGAAAGGCTGGAGCTCAACTCCAGTTTGGTATGGAAACTGTGTTATTAGATTATGATAGAGGTTAGCGGAATTCCTAATGTAGCGGTGGAATGCGTAGATATTAGGAGGAACACCAAAAGCGAAGGCAGCTAACTGGGTCATTAATGACACTGGTGCACGAAAGCGTGGGGAGCAAACAGG"] +1

#Micavibrionaceae
x_19<- clam_results_ps$Total_Diseased[clam_results_ps$Species=="TACTGGGGGAGCGAGCGTTGTTCGGAATCACTGGGCGTAAAGCGTGCGCAGGCGGTTTGGAAAGTCAGAAGTGAAATCCCAGAGCTCAACTCTGGAACTGCTTTTGAAACTTCCTTACTAGAGTTTGGTAGAGGTTGGGAGAATTCCTAGTGTAGAGGTGAAATTCGTAGATATTAGGAGGAATACCAGTGGCGTAGGCGCCCAACTGGACCATTACTGACGCTCAGGCACGAAAGCGTGGGGAGCAAACAGG"] +1 
y_19<- clam_results_ps$Total_Healthy[clam_results_ps$Species=="TACTGGGGGAGCGAGCGTTGTTCGGAATCACTGGGCGTAAAGCGTGCGCAGGCGGTTTGGAAAGTCAGAAGTGAAATCCCAGAGCTCAACTCTGGAACTGCTTTTGAAACTTCCTTACTAGAGTTTGGTAGAGGTTGGGAGAATTCCTAGTGTAGAGGTGAAATTCGTAGATATTAGGAGGAATACCAGTGGCGTAGGCGCCCAACTGGACCATTACTGACGCTCAGGCACGAAAGCGTGGGGAGCAAACAGG"] +1


pdf("CLAM_plot_with5labels.pdf", width = 8.25, height = 6,bg ="white")
plot(clam_results_ps, xlab = "Diseased samples (ASV abundance + 1)", ylab = "Healthy samples (ASV abundance + 1)", 
     pch = c(1,16,16,1), col=colors, col.lines = c("black", "black", "black"), 
     lty = c(2,2,2), cex=1.5, position = "topleft")
legend("topleft",legend = labels, pch = c(1,16,16,1), col=colors)
text(x=x_5,y=y_5, labels = "Cribrihabitans", pos=2)
text(x=x_12,y=y_12, labels = "Ferrimonas", pos=4)
text(x=x_16,y=y_16, labels = "Aurantivirga", pos=2)
text(x=x_13,y=y_13, labels = "Mycoplasma", pos=2)
text(x=x_19,y=y_19, labels = "Micavibrionaceae", pos=3)
dev.off()
```


Figure C: Differentially abundant taxa - Order level


```{r}
otu <- read.table("silva_nochloronomito_otu_table_ps_f2.txt",sep="\t",header=TRUE, row.names=1)
taxon <- read.table("silva_nochloronomito_taxa_table_ps_f2.txt",sep="\t",header=TRUE,row.names=1)
samples<-read.table("metadata_noblanks.txt",sep="\t",header=T,row.names=1)

OTU = otu_table(otu, taxa_are_rows=FALSE)
taxon<-as.matrix(taxon)
TAX = tax_table(taxon)
sampledata = sample_data(samples)
ps_f2 <- phyloseq(otu_table(otu, taxa_are_rows=FALSE), 
               sample_data(samples), 
               tax_table(taxon))
ps_f2 # 1202 taxa and 77 samples

ps_HH_DD<- subset_samples(ps_f2, Con == "H" | Con == "D")
ps_HH_DD #1202 taxa and 52 samples

ps_HH_DD_pruned <- prune_taxa(taxa_sums(ps_HH_DD) > 0, ps_HH_DD)
ps_HH_DD_pruned #1160 taxa and 52 samples

# agglomorate by order
ps_order<- tax_glom(ps_HH_DD_pruned, taxrank = "Order")
ps_order #139 orders and 52 samples

# Define the order of the conditions for testing
# In this order, the positive fold change values are increased in Diseased Tissue
sample_data(ps_order)$Con<-factor(sample_data(ps_order)$Con,levels=c("H","D"))

# DESEQ2 analysis
dds = phyloseq_to_deseq2(ps_order, ~ Con)
dds
#filter rows with very few counts
dds <- dds[ rowSums(counts(dds)) > 5, ]
cts <- counts(dds)
geoMeans <- apply(cts, 1, function(row) if (all(row == 0)) 0 else exp(mean(log(row[row != 0]))))
dds <- estimateSizeFactors(dds, geoMeans=geoMeans)
dds <- DESeq(dds,test="Wald", fitType="parametric")
res = results(dds, cooksCutoff = FALSE)
alpha = 0.01
sigtab = res[which(res$padj < alpha), ]
sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(ps_order)[rownames(sigtab), ], "matrix"))
head(sigtab)
dim(sigtab)
#save table of results
sig = as(sigtab, "matrix")
write.table(sig,"DESeq2_results_Order.txt",sep="\t",col.names=NA)
sig_dif<- read.table("DESeq2_results_Order.txt", header = TRUE)
colnames(sig_dif)[1]<- "ASV"

cols <- c("Proteobacteria"="#003049", "Bdellovibrionota"="#d62828", "Bacteroidota" = "#f77f00", "Firmicutes" = "#fcbf49", "Verrucomicrobiota" = "#eae2b7", "Patescibacteria" = "#0a9396")

#Create Figure for Significantly Different Taxa
pdf("FigureDEtaxa_Order.pdf",width=10,bg="white")
p1 <- ggplot(sig_dif,aes(log2FoldChange,Order,fill=Phylum))+
  geom_point(size=7, shape=21)+
  geom_errorbarh(aes(xmin=log2FoldChange-lfcSE, xmax=log2FoldChange+lfcSE),height=0.2)+
  scale_fill_manual(values=cols)+
  scale_y_discrete(limits=c("Verrucomicrobiales","Rickettsiales","Rhodobacterales","Pseudomonadales","Peptostreptococcales-Tissierellales","Oligoflexales","Mycoplasmatales","Gracilibacteria","Bacteroidales"))+
  labs(y= "Taxonomic Order")+
  theme(axis.title=element_text(size=14))+
  theme(legend.text=element_text(size=14))+
  theme(legend.title=element_text(size=16))+
  theme(axis.title.y = element_blank())+
  theme(axis.text=element_text(size=14, color="black"))+
  theme(legend.position = "bottom")+
  geom_vline(xintercept=0, linetype="dashed") +
  theme(panel.grid = element_blank()) +
  theme(panel.background = element_blank())
p1
dev.off()


```




Figure D - 5 Differentially Abundant taxa unique to OATLD


```{r}
otu <- read.table("silva_nochloronomito_otu_table_ps_f2.txt",sep="\t",header=TRUE, row.names=1)
taxon <- read.table("silva_nochloronomito_taxa_table_ps_f2.txt",sep="\t",header=TRUE,row.names=1)
samples<-read.table("metadata_noblanks.txt",sep="\t",header=T,row.names=1)

OTU = otu_table(otu, taxa_are_rows=FALSE)
taxon<-as.matrix(taxon)
TAX = tax_table(taxon)
sampledata = sample_data(samples)
ps_f2 <- phyloseq(otu_table(otu, taxa_are_rows=FALSE), 
               sample_data(samples), 
               tax_table(taxon))
ps_f2 # 1202 taxa and 77 samples
ps_f2_ra<- transform_sample_counts(ps_f2, function(OTU) OTU/sum(OTU))

otu_da = as(otu_table(ps_f2_ra), "matrix")
taxon_da = as(tax_table(ps_f2_ra), "matrix")
da<-t(otu_da)
da <- as.data.frame(da)
da <- tibble::rownames_to_column(da, "ASV")
taxon_da <- as.data.frame(taxon_da)
taxon_da <- tibble::rownames_to_column(taxon_da, "ASV")
taxon_da$Species<-NULL
da_tax <- merge(taxon_da, da, by="ASV", all=FALSE)

###Pull out 5 ASVs common to DESeq2 and Indicator species analyses AND are not in SCLTD custom blast

DA1 <- da_tax %>% filter(ASV == "TACGGAGGGGGTTAGCGTTGTTCGGAATTACTGGGCGTAAAGCGCGCGTAGGCGGATTGGAAAGTTGGGGGTGAAATCCCGGGGCTCAACCCCGGAACTGCCTTCAAAACTCCCAGTCTAGAGTTCGAGAGAGGTGAGTGGAATTCCGAGTGTAGAGGTGAAATTCGTAGATATTCGGAGGAACACCAGTGGCGAAGGCGGCTCACTGGCTCGATACTGACGCTGAGGTGCGAAAGTGTGGGGAGCAAACAGG") #Cribrihabitans ASV21
DA2 <- da_tax %>% filter(ASV == "TACGGAGGGTGCGAGCGTTAATCGGAATCACTGGGCGTAAAGCGCATGCAGGCGGTTTGCTAAGCGAGATGTGAAAGCCCCGGGCTTAACCTGGGAACTGCATTTCGAACTGGCGAACTAGAGTCTTGTAGAGGGGGGTAGAATTTCAGGTGTAGCGGTGAAATGCGTAGAGATCTGAAGGAATACCAGTGGCGAAGGCGGCCCCCTGGACAAAGACTGACGCTCAGATGCGAAAGCGTGGGGAGCAAACAGG") #Ferrimonas ASV64
DA3 <- da_tax %>% filter(ASV =="TACGGAGGGTGCAAGCGTTATCCGGAATCATTGGGTTTAAAGGGTCCGCAGGCGGTCAATTAAGTCAGAGGTGAAATCCCATAGCTTAACTATGGAACTGCCTTTGATACTGGTTGACTTGAGTTATACGGAAGTAGATAGAATAAGTAGTGTAGCGGTGAAATGCATAGATATTACTTAGAATACCGATTGCGAAGGCAGTCTACTACGTATATACTGACGCTCATGGACGAAAGCGTGGGGAGCGAACAGG") #Aurantivirga ASV123
DA4 <- da_tax %>% filter(ASV == "TACATAGGCCCCAAGCGTTATCCGGATTTACTGGGCGTAAAGAGTGCGCAGGTGATTTCACAAGTCTGTATTGAAAGGCTGGAGCTCAACTCCAGTTTGGTATGGAAACTGTGTTATTAGATTATGATAGAGGTTAGCGGAATTCCTAATGTAGCGGTGGAATGCGTAGATATTAGGAGGAACACCAAAAGCGAAGGCAGCTAACTGGGTCATTAATGACACTGGTGCACGAAAGCGTGGGGAGCAAACAGG") #Mycoplasma ASV80
DA5 <- da_tax %>% filter(ASV == "TACTGGGGGAGCGAGCGTTGTTCGGAATCACTGGGCGTAAAGCGTGCGCAGGCGGTTTGGAAAGTCAGAAGTGAAATCCCAGAGCTCAACTCTGGAACTGCTTTTGAAACTTCCTTACTAGAGTTTGGTAGAGGTTGGGAGAATTCCTAGTGTAGAGGTGAAATTCGTAGATATTAGGAGGAATACCAGTGGCGTAGGCGCCCAACTGGACCATTACTGACGCTCAGGCACGAAAGCGTGGGGAGCAAACAGG") #Micavibrionaceae AAV158
DA_all <-rbind(DA1,DA2,DA3,DA4,DA5)

# Merge with metadata for plotting aesthetics
samples <- as.data.frame(samples)
samples <- tibble::rownames_to_column(samples, "sample")
DA_long<-melt(DA_all,value.name="proportion",variable.name="sample",id.vars=c("ASV","Kingdom","Phylum","Class","Order","Family","Genus"))

DAplot <- merge(DA_long,samples,by="sample", all=TRUE)
# reduce decimal places in proporation column
DAplot$proportion<-round(DAplot$proportion,3)

palette2<- c("Diseased" = "#d1495b", "Unaffected" = "#edae49", "Healthy" = "#00798c")
DAplot$Condition<-factor(DAplot$Condition, levels=c("Healthy", "Unaffected", "Diseased"))
DAplot$Con<-factor(DAplot$Con, levels=c("H", "U", "D"))
DAplot$Genus<-factor(DAplot$Genus, levels=c("Cribrihabitans", "Ferrimonas", "Aurantivirga","Mycoplasma","Micavibrionaceae"))
theme_set(theme_bw()+theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank()))

p5<-ggplot(DAplot,aes(x=Con,y=proportion,fill=Condition))+
  geom_boxplot(alpha = 0.6)+
  geom_point(position=position_jitter(width=.1, height=0),aes(fill=Condition),size=4,pch=21) +
  facet_wrap(Genus~.,scales="free", nrow=1)+
  theme(axis.text.x = element_text(colour="black"))+
  theme(axis.text.y = element_text(colour="black"))+
  theme(axis.text.x = element_text(size = 12))+
  theme(axis.text.y = element_text(size = 12))+
  theme(axis.title.y = element_text(size = 14))+
  theme(strip.text.x = element_text(face="italic", size=12), strip.background=element_rect(fill="white"))+
  theme(axis.title.x = element_blank())+
  ylab("Relative Abundance")+
  scale_fill_manual(values=palette2)
p5

pdf("OATLD_DE.pdf", width = 11, height = 4, bg ="white")
p5
dev.off()

```


